spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vatera_db
    username: vatera
    password: vatera
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
